const patientAddressFields = [
  {
    labelText: "Street 1",
    labelFor: "txtStreet1",
    id: "txtStreet1",
    name: "home_street1",
    type: "text",
    autoComplete: "home_street1",
    isRequired: true,
    placeholder: "Street 1",
  },
  {
    labelText: "Street 2",
    labelFor: "txtStreet2",
    id: "txtStreet2",
    name: "home_street2",
    type: "text",
    autoComplete: "home_street2",
    isRequired: false,
    placeholder: "Street 2",
  },
  {
    labelText: "City",
    labelFor: "txtCity",
    id: "txtCity",
    name: "home_city",
    type: "text",
    autoComplete: "home_city",
    isRequired: true,
    placeholder: "City",
  },
  {
    labelText: "State",
    labelFor: "txtState",
    id: "txtState",
    name: "home_state",
    type: "text",
    autoComplete: "home_state",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "Postal Code",
    labelFor: "txtPostalCode",
    id: "txtPostalCode",
    name: "home_postal_code",
    type: "text",
    autoComplete: "home_postal_code",
    isRequired: true,
    placeholder: "Postal Code",
  },
  {
    labelText: "Country",
    labelFor: "txtCountry",
    id: "txtCountry",
    name: "home_country",
    type: "text",
    autoComplete: "home_country",
    isRequired: true,
    placeholder: "Country",
  },
];

const patientContactFields = [
  {
    labelText: "Home",
    labelFor: "txtHomePhone",
    id: "txtHomePhone",
    name: "home_phone",
    type: "text",
    autoComplete: "home_phone",
    isRequired: true,
    placeholder: "Home",
  },
  {
    labelText: "Work",
    labelFor: "txtWorkPhone",
    id: "txtWorkPhone",
    name: "work_phone",
    type: "text",
    autoComplete: "work_phone",
    isRequired: false,
    placeholder: "Work",
  },
];

const patientNameFields = [
  {
    labelText: "First Name",
    labelFor: "txtFirstName",
    id: "txtFirstName",
    name: "FirstName",
    type: "text",
    autoComplete: "FirstName",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Middle Name",
    labelFor: "txtMiddleName",
    id: "txtMiddleName",
    name: "MiddleName",
    type: "text",
    autoComplete: "MiddleName",
    isRequired: false,
    placeholder: "Middle Name",
  },
  {
    labelText: "Last Name",
    labelFor: "txtLastName",
    id: "txtLastName",
    name: "LastName",
    type: "text",
    autoComplete: "LastName",
    isRequired: true,
    placeholder: "Last Name",
  },
  {
    labelText: "Suffix",
    labelFor: "txtSuffix",
    id: "txtSuffix",
    name: "Suffix",
    type: "text",
    autoComplete: "Suffix",
    isRequired: false,
    placeholder: "Suffix",
  }
];


export { patientAddressFields, patientContactFields, patientNameFields };
